- name: SOFT INSTALL
  hosts: ws
  gather_facts: false
  vars:
    msi_dir: \\diskstation\software\msi\
  tasks:
    - name: Install 7zip
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install SublimeText
      win_chocolatey:
        name: sublimetext3
        state: present

    - name: Install WinSCP
      win_chocolatey:
        name: winscp
        state: present

    - name: Install FileZilla
      win_chocolatey:
        name: filezilla
        state: present

    - name: Install ImageMagick
      win_chocolatey:
        name: imagemagick
        state: present

    - name: Install K-Lite
      win_chocolatey:
        name: k-litecodecpackmega
        state: present

    - name: Install VLC
      win_chocolatey:
        name: vlc
        state: present

    - name: Install FoxitReader
      win_chocolatey:
        name: foxitreader
        state: present

    - name: Install Paint.Net
      win_chocolatey:
        name: paint.net
        state: present

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Install FireFox
      win_chocolatey:
        name: firefox
        state: present

    - name: Install ESET
      win_package:
        path: "{{ msi_dir }}ESMC_Installer_x64_ru_RU.exe"
        product_id: ESMC
        arguments: --silent --accepteula
        state: present
        register: eset_install
        expected_return_code: [0, 3010, 5002]

    - name: Install MSO
      win_command: setup.exe /configure configuration-Office2019Enterprise.xml
      args:
        chdir: \\diskstation\software\office\office2019\
